apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    {{- include "api.labels" . | indent 4}}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.api.servicePort | default 80 }}
    targetPort: {{ .Values.api.port | default 3001 }}