api:
  replicaCount: 1
  # image: 
  port: 3001
  servicePort: 80
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 250m
      memory: 250Mi
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    # className: nginx
    hosts:
    - host: '' # Leave this empty if you're not going to associate a domain with your ingress public IP
      paths:
      - path: /api/(.*)
        pathType: ImplementationSpecific

      
      
  

