name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gbh-demo-api:${{ github.sha }}

      - name: Setup kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Setup Helm
        uses: azure/setup-helm@v4
      
      - name: Deploy App Helm Chart
        run: |
          helm upgrade gbh-demo-api .helm/ \
          --install \
          --namespace=${{ vars.NAMESPACE }} \
          --create-namespace \
          -- set api.image=${{ vars.DOCKERHUB_USERNAME }}/gbh-demo-api:${{ github.sha }}